"""Generate the standard validation-results DDL for a data product.

The Trust Engine publishes its per-area trust map (wire schema 2.1) into the
product's Observability module through ``--publish-validation``. The landing
objects (``validation_run`` and ``validation_area`` tables, ``validation_latest``
and ``validation_trust_map`` views) are the standard's, not the engine's, but
every product needs a copy bound to its own prefix. This module renders that
copy so nothing is hand-edited per product.

Tables land in ``{prefix}_OBS_STD_T`` and views in ``{prefix}_OBS_STD_V`` by
default; both can be overridden for products that bind object placement
differently.
"""

from __future__ import annotations

import re

from ai_native_data_product_trust_engine.layout import SOURCE_DERIVATION, Layout, derive_layout
from ai_native_data_product_trust_engine.trust_publish import default_validation_database

_IDENTIFIER = re.compile(r"^[A-Za-z][A-Za-z0-9_]*$")

# Placeholders are deliberately not Python format fields: the SQL contains no
# braces, but a literal replace keeps the template readable as plain SQL.
_TABLE_DB = "__TABLE_DB__"
_VIEW_DB = "__VIEW_DB__"
_ACL_DB = "__ACL_DB__"


def default_validation_view_database(prefix: str, layout: Layout | None = None) -> str:
    layout = layout or derive_layout(prefix)
    return layout.observability_database


def default_validation_acl_database(prefix: str, layout: Layout | None = None) -> str:
    """The access-layer view database: the declared Observability consumer container, if any."""
    layout = layout or derive_layout(prefix)
    if layout.source_of("observability_consumer_database") != SOURCE_DERIVATION:
        return layout.observability_consumer_database
    return f"{prefix}_OBS_ACL_V"


def validation_ddl(
    prefix: str,
    table_database: str | None = None,
    view_database: str | None = None,
    acl_view_database: str | None = None,
    layout: Layout | None = None,
) -> str:
    """Render the validation_run / validation_area tables and their views for ``prefix``."""
    table_db = _database_identifier(
        table_database or default_validation_database(prefix, layout)
    )
    view_db = _database_identifier(
        view_database or default_validation_view_database(prefix, layout)
    )
    acl_db = _database_identifier(
        acl_view_database or default_validation_acl_database(prefix, layout)
    )
    return (
        _TEMPLATE.replace(_TABLE_DB, table_db).replace(_VIEW_DB, view_db).replace(_ACL_DB, acl_db)
    )


def _database_identifier(value: str) -> str:
    if not _IDENTIFIER.fullmatch(value or ""):
        msg = (
            f"[ADPTrust.InvalidTrustTable] Invalid validation database name {value!r}. "
            "Suggested action: use a single Teradata database name such as "
            "{ProductPrefix}_OBS_STD_T."
        )
        raise ValueError(msg)
    return value


_TEMPLATE = """-- ======================================================================
-- 01-validation-run.sql  (tables in __TABLE_DB__, views in __VIEW_DB__)
-- ======================================================================
-- Validation: run record (Teradata). Binding of the validation result contract in design/patterns/validation.md.
-- The run-level summary; the per-area trust map is 03-validation-area.sql.
-- Operational evidence in the Observability module; append-only (EVENT_APPEND_ONLY).
-- __TABLE_DB__ is bound by object-placement for this product.
-- Generated by: python -m ai_native_data_product_trust_engine validation-ddl --prefix <ProductPrefix>

CREATE MULTISET TABLE __TABLE_DB__.validation_run
(
    product_prefix VARCHAR(128) CHARACTER SET LATIN NOT NULL,

    -- Producer identity (canonical schema 2.0)
    producer_id VARCHAR(64) CHARACTER SET LATIN NOT NULL,
    producer_version VARCHAR(32) CHARACTER SET LATIN,
    profile_id VARCHAR(64) CHARACTER SET LATIN,
    profile_version VARCHAR(32) CHARACTER SET LATIN,
    source_format VARCHAR(20) CHARACTER SET LATIN NOT NULL DEFAULT 'NATIVE',
    payload_schema_version VARCHAR(8) CHARACTER SET LATIN NOT NULL DEFAULT '2.1',

    -- Run identity
    run_id VARCHAR(64) CHARACTER SET LATIN NOT NULL,
    started_dts TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    completed_dts TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    -- Advisory product-level summary of the map (section 4.4). Not permission, not a decision.
    trust_status VARCHAR(16) CHARACTER SET LATIN NOT NULL,
    -- Deprecated at schema 2.1: kept so a 2.0 reader still parses the record. A 2.1 producer
    -- publishes 1 and no consumer branches on it; the trust map carries what mattered here.
    agent_use_allowed BYTEINT NOT NULL CHECK (agent_use_allowed IN (0, 1)),

    -- Check totals (status axis) and counts by severity
    total_checks INTEGER NOT NULL,
    passed_count INTEGER NOT NULL,
    failed_count INTEGER NOT NULL,
    error_count INTEGER NOT NULL,
    critical_failure_count INTEGER NOT NULL,
    error_failure_count INTEGER NOT NULL,

    -- Scores (null = not assessed)
    data_product_trust_score INTEGER,
    performance_readiness_score INTEGER,
    operational_readiness_score INTEGER,

    -- Detail (capped; true totals in the count columns)
    repair_candidate_count INTEGER NOT NULL,
    failed_checks_json JSON(32000) CHARACTER SET UNICODE,
    repair_candidates_json JSON(32000) CHARACTER SET UNICODE,

    -- Evidence expiry (null = product/consumer default window applies)
    evidence_expires_dts TIMESTAMP(6) WITH TIME ZONE,

    -- Row audit (temporal-lifecycle pattern, EVENT_APPEND_ONLY)
    created_dts TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_dts TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
)
PRIMARY INDEX (product_prefix, completed_dts);

-- Declares temporal_pattern = EVENT_APPEND_ONLY in the Semantic entity metadata.
-- Column comments required on deploy (RichMetadata). Statistics:
COLLECT STATISTICS
      COLUMN (product_prefix)
    , COLUMN (producer_id)
    , COLUMN (product_prefix, producer_id)
    , COLUMN (product_prefix, completed_dts)
ON __TABLE_DB__.validation_run;

-- ======================================================================
-- 03-validation-area.sql  (tables in __TABLE_DB__, views in __VIEW_DB__)
-- ======================================================================
-- Validation: trust-map area table (Teradata). Binding of the area record in design/patterns/validation.md section 3.2.
-- One row per run per area: the per-area picture a consumer reads before using that area.
-- Operational evidence in the Observability module; append-only (EVENT_APPEND_ONLY).
-- __TABLE_DB__ is bound by object-placement for this product.

CREATE MULTISET TABLE __TABLE_DB__.validation_area
(
    -- Parentage: the run this entry belongs to (__TABLE_DB__.validation_run)
    product_prefix VARCHAR(128) CHARACTER SET LATIN NOT NULL,
    producer_id VARCHAR(64) CHARACTER SET LATIN NOT NULL,
    run_id VARCHAR(64) CHARACTER SET LATIN NOT NULL,

    -- The area (section 4.1)
    scope_kind VARCHAR(16) CHARACTER SET LATIN NOT NULL
        CHECK (scope_kind IN ('MODULE', 'ENTITY', 'PATTERN', 'CAPABILITY', 'PRODUCT')),
    scope_id VARCHAR(128) CHARACTER SET LATIN NOT NULL,

    -- Coverage: what the profile defines here, and what actually ran (section 4.2)
    checks_expected INTEGER NOT NULL,
    checks_ran INTEGER NOT NULL,

    -- Outcomes within the area (status axis) and severity counts
    passed_count INTEGER NOT NULL,
    failed_count INTEGER NOT NULL,
    error_count INTEGER NOT NULL,
    critical_failure_count INTEGER NOT NULL,
    error_failure_count INTEGER NOT NULL,

    -- Verdict for the area (section 4.3): informs use, never withholds it
    area_status VARCHAR(16) CHARACTER SET LATIN NOT NULL
        CHECK (area_status IN ('pass', 'fail', 'partial', 'not-validated', 'no-evidence')),
    confidence VARCHAR(8) CHARACTER SET LATIN NOT NULL
        CHECK (confidence IN ('strong', 'partial', 'weak', 'unknown')),

    -- Guidance: required unless confidence is 'strong' (VAL-17)
    open_gaps VARCHAR(1000) CHARACTER SET UNICODE,
    recommended_action VARCHAR(1000) CHARACTER SET UNICODE,

    -- Inherited from the run, so the latest-per-area projection is deterministic
    completed_dts TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    -- Row audit (temporal-lifecycle pattern, EVENT_APPEND_ONLY)
    created_dts TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_dts TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
)
PRIMARY INDEX (product_prefix, scope_kind, scope_id);

COMMENT ON TABLE __TABLE_DB__.validation_area IS
'Trust map - one append-only row per validation run per area (module, entity, pattern, capability, product): coverage, outcome, confidence, and what would raise it. Read the areas a query touches; nothing here blocks use.';
COMMENT ON COLUMN __TABLE_DB__.validation_area.product_prefix IS 'Product identity the run evaluated; joins to validation_run.';
COMMENT ON COLUMN __TABLE_DB__.validation_area.producer_id IS 'Producing validator; the trust-authoritative producer named in orientation owns the map.';
COMMENT ON COLUMN __TABLE_DB__.validation_area.run_id IS 'Run this entry belongs to; joins to validation_run.run_id.';
COMMENT ON COLUMN __TABLE_DB__.validation_area.scope_kind IS 'What kind of area this entry describes: MODULE, ENTITY, PATTERN, CAPABILITY or PRODUCT.';
COMMENT ON COLUMN __TABLE_DB__.validation_area.scope_id IS 'Identity of the area - module or pattern anchor, qualified entity, capability name, or the product prefix. Taken from the corpus and the Semantic catalogue, never derived from an object name.';
COMMENT ON COLUMN __TABLE_DB__.validation_area.checks_expected IS 'Checks the profile defines for this area; 0 means none is defined, which reads as no-evidence rather than as nothing wrong.';
COMMENT ON COLUMN __TABLE_DB__.validation_area.checks_ran IS 'How many of the expected checks executed in this run; coverage is checks_ran / checks_expected, derived on read.';
COMMENT ON COLUMN __TABLE_DB__.validation_area.passed_count IS 'Checks in this area with status PASSED.';
COMMENT ON COLUMN __TABLE_DB__.validation_area.failed_count IS 'Checks in this area with status FAILED, any severity.';
COMMENT ON COLUMN __TABLE_DB__.validation_area.error_count IS 'Checks in this area that could not execute (status ERROR).';
COMMENT ON COLUMN __TABLE_DB__.validation_area.critical_failure_count IS 'Failed or errored checks in this area at CRITICAL severity.';
COMMENT ON COLUMN __TABLE_DB__.validation_area.error_failure_count IS 'Failed or errored checks in this area at ERROR severity.';
COMMENT ON COLUMN __TABLE_DB__.validation_area.area_status IS 'What happened here: pass, fail, partial (clean but incomplete cover), not-validated (checks defined, none ran), no-evidence (no check defined).';
COMMENT ON COLUMN __TABLE_DB__.validation_area.confidence IS 'How far this entry supports use of the area: strong, partial, weak, unknown. Severity-weighted and coverage-aware; advisory to the consumer, never permission.';
COMMENT ON COLUMN __TABLE_DB__.validation_area.open_gaps IS 'What is uncovered or unproven in this area. Required unless confidence is strong.';
COMMENT ON COLUMN __TABLE_DB__.validation_area.recommended_action IS 'What would raise confidence here - a check to write, a re-run, a metadata backfill, a design decision to settle. Required unless confidence is strong.';
COMMENT ON COLUMN __TABLE_DB__.validation_area.completed_dts IS 'Completion instant inherited from the run, so latest-per-area ordering matches latest-per-run.';
COMMENT ON COLUMN __TABLE_DB__.validation_area.created_dts IS 'When this row was appended.';
COMMENT ON COLUMN __TABLE_DB__.validation_area.updated_dts IS 'When this row was last touched; append-only evidence, so equal to created_dts.';

-- Declares temporal_pattern = EVENT_APPEND_ONLY in the Semantic entity metadata.
-- Apply the comments above as their own step, then collect statistics:
COLLECT STATISTICS
      COLUMN (product_prefix)
    , COLUMN (producer_id)
    , COLUMN (run_id)
    , COLUMN (product_prefix, producer_id)
    , COLUMN (scope_kind, scope_id)
    , COLUMN (product_prefix, scope_kind, scope_id)
    , COLUMN (product_prefix, completed_dts)
ON __TABLE_DB__.validation_area;

-- ======================================================================
-- 02-views.sql  (tables in __TABLE_DB__, views in __VIEW_DB__)
-- ======================================================================
-- Validation: latest-run view (Teradata). Binding of the run record in design/patterns/validation.md section 3.1.
-- Latest-per-(product, producer) projection. The deterministic tie-break
-- (completed_dts DESC, run_id DESC) is part of the contract (VAL-09).
-- This is the run-level summary; the per-area trust map a consumer reads is 04-trust-map-views.sql.
-- __TABLE_DB__ is bound by object-placement for this product.

REPLACE VIEW __VIEW_DB__.validation_latest
AS
LOCKING ROW FOR ACCESS
SELECT
      product_prefix
    , producer_id
    , producer_version
    , profile_id
    , profile_version
    , source_format
    , payload_schema_version
    , run_id
    , started_dts
    , completed_dts
    , trust_status
    , agent_use_allowed
    , total_checks
    , passed_count
    , failed_count
    , error_count
    , critical_failure_count
    , error_failure_count
    , data_product_trust_score
    , performance_readiness_score
    , operational_readiness_score
    , repair_candidate_count
    , failed_checks_json
    , repair_candidates_json
    , evidence_expires_dts
FROM __TABLE_DB__.validation_run
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY product_prefix, producer_id
    ORDER BY completed_dts DESC, run_id DESC
) = 1;

-- The authoritative summary is the row whose producer_id matches the trust-authoritative
-- producer designated in the product's orientation metadata; other rows are evidence.
-- trust_status here is advisory: a consumer deciding how far to rely on something reads
-- validation_trust_map for the areas it is about to query.

-- ======================================================================
-- 04-trust-map-views.sql  (tables in __TABLE_DB__, views in __VIEW_DB__)
-- ======================================================================
-- Validation: trust-map view (Teradata). Binding of the trust map and its consumption contract
-- in design/patterns/validation.md sections 4, 9, 10, 11.
-- Latest-per-(product, producer, area) projection, with coverage derived on read. The deterministic
-- tie-break (completed_dts DESC, run_id DESC) is part of the contract (VAL-09).
-- A producer publishing no area rows is at wire schema 2.0; its run record projects a single
-- PRODUCT-scope entry here, capped at 'partial' confidence, so the map has one shape everywhere.
-- Staleness (section 11) is evaluated per area against the run that actually produced it, not against
-- the producer's latest run: two areas in this map can come from different runs, so evaluating
-- staleness against "the latest run" would grade older evidence by a newer run's clock.
-- __TABLE_DB__ is bound by object-placement for this product.

REPLACE VIEW __VIEW_DB__.validation_trust_map
AS
LOCKING ROW FOR ACCESS
SELECT
      a.product_prefix
    , a.producer_id
    , a.run_id
    , a.scope_kind
    , a.scope_id
    , a.checks_expected
    , a.checks_ran
    , CASE WHEN a.checks_expected > 0
           THEN CAST(a.checks_ran AS DECIMAL(9, 4)) / a.checks_expected
      END AS coverage_ratio
    , a.passed_count
    , a.failed_count
    , a.error_count
    , a.critical_failure_count
    , a.error_failure_count
    , a.area_status
    -- Stale evidence reads at 'unknown' whatever it recorded (section 11); the run's own declared
    -- expiry wins, else the default 7-day window from the completion this area belongs to.
    , CASE WHEN a.evidence_is_stale = 1 THEN 'unknown' ELSE a.confidence END AS confidence
    , a.confidence AS recorded_confidence
    , a.evidence_is_stale
    , a.open_gaps
    , CASE WHEN a.evidence_is_stale = 1
           THEN 'Evidence has expired; re-run the validator for this area.'
           ELSE a.recommended_action
      END AS recommended_action
    , a.recommended_action AS recorded_recommended_action
    , a.completed_dts
    , 'PUBLISHED' AS map_source
-- The latest run per area is resolved in a derived table: QUALIFY is scoped to its own query
-- block, and nesting it keeps the projection unambiguous across the UNION below. Joined to its
-- own parent run (not the producer's latest run) so staleness reflects the evidence's own age.
FROM (
    SELECT
          la.product_prefix, la.producer_id, la.run_id
        , la.scope_kind, la.scope_id
        , la.checks_expected, la.checks_ran
        , la.passed_count, la.failed_count, la.error_count
        , la.critical_failure_count, la.error_failure_count
        , la.area_status, la.confidence
        , la.open_gaps, la.recommended_action
        , la.completed_dts
        , CASE WHEN COALESCE(r.evidence_expires_dts, la.completed_dts + INTERVAL '7' DAY)
                    < CURRENT_TIMESTAMP(6)
               THEN 1 ELSE 0
          END AS evidence_is_stale
    FROM __TABLE_DB__.validation_area AS la
    INNER JOIN __TABLE_DB__.validation_run AS r
            ON  r.product_prefix = la.product_prefix
            AND r.producer_id    = la.producer_id
            AND r.run_id         = la.run_id
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY la.product_prefix, la.producer_id, la.scope_kind, la.scope_id
        ORDER BY la.completed_dts DESC, la.run_id DESC
    ) = 1
) AS a

UNION ALL

-- Wire schema 2.0 / 1.0 fallback: derive one PRODUCT entry from the run counts (section 10), staleness
-- evaluated against this same run since there is only one row to derive it from.
SELECT
      v.product_prefix
    , v.producer_id
    , v.run_id
    , 'PRODUCT' AS scope_kind
    , v.product_prefix AS scope_id
    , v.total_checks AS checks_expected
    , v.total_checks AS checks_ran
    , CASE WHEN v.total_checks > 0 THEN CAST(1 AS DECIMAL(9, 4)) END AS coverage_ratio
    , v.passed_count
    , v.failed_count
    , v.error_count
    , v.critical_failure_count
    , v.error_failure_count
    , CASE WHEN v.total_checks = 0                              THEN 'no-evidence'
           WHEN v.failed_count + v.error_count > 0              THEN 'fail'
           ELSE 'pass'
      END AS area_status
      -- Capped at 'partial': a run-level pass says nothing about which areas it covered.
    , CASE WHEN COALESCE(v.evidence_expires_dts, v.completed_dts + INTERVAL '7' DAY)
                < CURRENT_TIMESTAMP(6)                           THEN 'unknown'
           WHEN v.total_checks = 0                               THEN 'unknown'
           WHEN v.critical_failure_count + v.error_failure_count > 0
             OR v.error_count > 0                                THEN 'weak'
           ELSE 'partial'
      END AS confidence
    , CASE WHEN v.total_checks = 0                              THEN 'unknown'
           WHEN v.critical_failure_count + v.error_failure_count > 0
             OR v.error_count > 0                               THEN 'weak'
           ELSE 'partial'
      END AS recorded_confidence
    , CASE WHEN COALESCE(v.evidence_expires_dts, v.completed_dts + INTERVAL '7' DAY)
                < CURRENT_TIMESTAMP(6) THEN 1 ELSE 0
      END AS evidence_is_stale
    , 'Producer publishes no per-area map (wire schema 2.0), so trust is stated for the whole product only and cannot be resolved to the area a query touches.' AS open_gaps
    , CASE WHEN COALESCE(v.evidence_expires_dts, v.completed_dts + INTERVAL '7' DAY)
                < CURRENT_TIMESTAMP(6)
           THEN 'Evidence has expired; re-run the validator for this product.'
           ELSE 'Upgrade the validator to publish validation_area entries at wire schema 2.1.'
      END AS recommended_action
    , 'Upgrade the validator to publish validation_area entries at wire schema 2.1.' AS recorded_recommended_action
    , v.completed_dts
    , 'DERIVED' AS map_source
FROM __VIEW_DB__.validation_latest AS v
-- Scoped to explicit legacy versions (never a lexical '< 2.1', which breaks on a future major
-- version) and to THIS run: a malformed 2.1 run that published no area rows must fail VAL-18,
-- not be quietly re-dressed as a legacy product. An older producer's historical 2.1 area rows
-- do not suppress the fallback for a current 2.0 run from the same producer, because the
-- existence check is scoped to v.run_id, not to the producer as a whole.
WHERE v.payload_schema_version IN ('1.0', '2.0')
  AND NOT EXISTS (
    SELECT 1
    FROM __TABLE_DB__.validation_area AS a
    WHERE a.product_prefix = v.product_prefix
      AND a.producer_id    = v.producer_id
      AND a.run_id         = v.run_id
);

COMMENT ON VIEW __VIEW_DB__.validation_trust_map IS
'Trust map - latest entry per product, producer and area; coverage and staleness derived on read against the evidence''s own run. Read the areas a query touches, proceed, and disclose confidence and gaps. Nothing here withholds use.';

-- The authoritative map is the set of rows whose producer_id matches the trust-authoritative
-- producer designated in the product's orientation metadata; other producers' rows are evidence.
-- Absent a designation, take the most cautious entry per area across producers and say so
-- (see consumer-queries.sql).

-- ======================================================================
-- 05-acl-trust-map-view.sql  (access-layer view in __ACL_DB__)
-- ======================================================================
-- Access-layer exposure of the validation results. Consumers and agents (and the Data Product
-- Browser, via the registry's observability_view_database) are granted the ACL_V tier, so these
-- are the views they read: validation_latest for the run-level summary (the Browser's Trust page
-- renders only when it finds this row) and validation_trust_map for which areas may be relied on.
-- Thin projections of the __VIEW_DB__ views: no logic lives here, so staleness and coverage
-- stay defined in one place.

REPLACE VIEW __ACL_DB__.validation_latest
AS
LOCKING ROW FOR ACCESS
SELECT
      product_prefix
    , producer_id
    , producer_version
    , profile_id
    , profile_version
    , source_format
    , payload_schema_version
    , run_id
    , started_dts
    , completed_dts
    , trust_status
    , agent_use_allowed
    , total_checks
    , passed_count
    , failed_count
    , error_count
    , critical_failure_count
    , error_failure_count
    , data_product_trust_score
    , performance_readiness_score
    , operational_readiness_score
    , repair_candidate_count
    , failed_checks_json
    , repair_candidates_json
    , evidence_expires_dts
FROM __VIEW_DB__.validation_latest;

COMMENT ON VIEW __ACL_DB__.validation_latest IS
'Latest validation run per product and producer - advisory run summary (scores, check counts, failed checks). For area-level trust read validation_trust_map. Informs use, never blocks it.';

REPLACE VIEW __ACL_DB__.validation_trust_map
AS
LOCKING ROW FOR ACCESS
SELECT
      product_prefix
    , producer_id
    , run_id
    , scope_kind
    , scope_id
    , checks_expected
    , checks_ran
    , coverage_ratio
    , passed_count
    , failed_count
    , error_count
    , critical_failure_count
    , error_failure_count
    , area_status
    , confidence
    , recorded_confidence
    , evidence_is_stale
    , open_gaps
    , recommended_action
    , recorded_recommended_action
    , completed_dts
    , map_source
FROM __VIEW_DB__.validation_trust_map;

COMMENT ON VIEW __ACL_DB__.validation_trust_map IS
'Trust map for agents - latest entry per product, producer and area. Read area_status, confidence, open_gaps and recommended_action before using an area; stale evidence reads as unknown. Advisory: informs reliance, never withholds use.';
"""
